receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:
      process:
  prometheus:
    config:
      global:
        external_labels:
          p8s_logzio_name: es_modi_local
      scrape_configs:
        - job_name: 'elasticsearch'
          scrape_interval: 15s
          static_configs:
            - targets: ['localhost:9114']

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: https://listener.logz.io:8053
    timeout: 30s
    headers:
      Authorization: Bearer IQraITRqPeLFeLfCwMjPDZAAWlVlyrur
  logging:
    loglevel: info

service:
  pipelines:
    metrics:
      receivers:
        - prometheus
        - hostmetrics
      exporters:
        - logging
        - prometheusremotewrite